# Generated by Django 5.0.2 on 2024-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_palace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=21),
        ),
    ]
